[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.4",
]

[project]
name = "SwiftPY"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "uvicorn[standard]>=0.52.4",
    "asyncpg>=0.30.0",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = ["asyncpg"]
ignore_missing_imports = true

[project.scripts]
swiftpy = "swiftpy.console.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true